FROM golang:1.20
WORKDIR /usr/src/app

# ローカルのgo.mod、go.sumをコピーし、go mod downloadによりモジュールのキャッシュ作成
# go mod verifyにて依存関係を照合
COPY go.mod go.sum ./
RUN go mod download && go mod verify
COPY . .

RUN apt-get update \
&& apt-get install -y git \
&& rm -rf /var/lib/apt/lists/* \
# ホットリロード  Air
&& go install  github.com/cosmtrek/air@v1.44.0 \
# Language Server
&& go install -v golang.org/x/tools/gopls@latest \
# デバッグ
&& go install -v github.com/go-delve/delve/cmd/dlv@latest

# Airにて実行(事前にルートディレクトリに".air.toml"を準備)
CMD ["air", "-c", ".air.toml"]