FROM golang:1.20
WORKDIR /usr/src/app

# ローカルのgo.mod、go.sumをコピーし、go mod downloadによりモジュールのキャッシュ作成
# go mod verifyにて依存関係を照合
COPY go.mod go.sum ./
RUN go mod download && go mod verify
COPY . .

RUN apt-get update \
&& apt-get install -y git \
&& rm -rf /var/lib/apt/lists/* \
# Webフレームワーク  gin
&& go get github.com/gin-gonic/gin \
# ORM  GORM
&& go get github.com/jinzhu/gorm \
# MySQLドライバー
&& go get github.com/go-sql-driver/mysql \
# GORM MySQLドライバー
&& go get gorm.io/driver/mysql \
# ホットリロード  Air
&& go install  github.com/cosmtrek/air@v1.44.0

# Airにて実行(事前にルートディレクトリに".air.toml"を準備)
CMD ["air", "-c", ".air.toml"]